version: '3'
services:
  codesys:
    build: 
      context: ./codesys  
      dockerfile: Dockerfile
    container_name: codesys_control
    volumes:
      - ./codesys/logs/:/var/opt/codesys/
      # https://www.wibu.com/magazine/keynote-articles/article/detail/codemeter-support-for-docker.html
      - /var/run/docker.sock:/var/run/docker.sock  # Access to Docker socket (critical according to the article above)
    user: nxbdocker
    network_mode: host
    privileged: true
    environment:
      - SSHPORT=2222

  api:
    build: 
      context: ./web  
      dockerfile: Dockerfile.api
    volumes:
      - ./web:/app
      - /var/lib/docker/containers:/var/lib/docker/containers:ro 
      - ./logs:/var/log/codesys
    depends_on:
      - codesys
    environment:
      - CODESYS_CONTAINER=codesys_control
      - CODEMETER_HOST=codesys_control
    network_mode: host

  nginx:
    build: 
      context: ./web 
      dockerfile: Dockerfile.web
    volumes:
      - ./web/default.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    network_mode: host
