version: '3'
services:
  codesys:
    build: 
      context: ./codesys  
      dockerfile: Dockerfile
    container_name: codesys_control
    volumes:
      - ./codesys/src:/var/opt/codesys
      - ./logs:/var/log/codesys
      ######   Uncomment and enter the path to licence storage ! ##################
      #- codemeter_license:/path/to/license/storage  # Add path to license storage
      # https://www.wibu.com/magazine/keynote-articles/article/detail/codemeter-support-for-docker.html
      - /var/run/docker.sock:/var/run/docker.sock  # Access to Docker socket (critical according to the article above)
    ports:
      - "2222:22"
      - "11740:11740"
    user: nxbdocker
    # networks:
    #   - codemeter_net  # Join the custom network

  api:
    build: 
      context: ./web  
      dockerfile: Dockerfile.api
    volumes:
      - ./web:/app
      - /var/lib/docker/containers:/var/lib/docker/containers:ro 
      - ./logs:/var/log/codesys
    ports:
      - "5000:5000"
    depends_on:
      - codesys
    environment:
      - CODESYS_CONTAINER=codesys_control
      - CODEMETER_HOST=codesys_control 
    # networks:
    #   - codemeter_net 

  nginx:
    build: 
      context: ./web 
      dockerfile: Dockerfile.web
    volumes:
      - ./web/default.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - api
    # networks:
    #   - codemeter_net  

networks:
    default:
      - driver: host
# codemeter_net:
#     driver: bridge

####### Uncomment when licence storage path is set above! ########
#volumes:
#  codemeter_license:  # Define the license volume
#    driver: local
