FROM nginx:latest

# Remove the default nginx configuration
RUN rm -f /etc/nginx/conf.d/default.conf

COPY default.conf /etc/nginx/conf.d/

COPY index.html /usr/share/nginx/html/index.html

RUN cat /etc/nginx/nginx.conf &&  /etc/nginx/conf.d/default.conf 

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
