FROM nginx:latest

# Remove the default nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

COPY default.conf /etc/nginx/conf.d/

COPY index.html /usr/share/nginx/html/index.html

EXPOSE 80

RUN cat /etc/nginx/nginx.conf
CMD ["nginx", "-g", "daemon off;"]
