FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY flask-app.py index.html /assets/* .

# Expose the Flask port
EXPOSE 5000

CMD ["python", "flask-app.py"]
