FROM nginx:latest

RUN apt-get update && apt-get install -y curl nano
# Remove the default nginx configuration
RUN rm -f /etc/nginx/conf.d/default.conf

COPY default.conf /etc/nginx/conf.d/

COPY assets/favicon/* /usr/share/nginx/html/assets/favicon/
COPY index.html /usr/share/nginx/html/index.html
COPY main.js /usr/share/nginx/html/main.js 
COPY error-db.json /usr/share/nginx/html/error-db.json 

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
